# ============== Sample configuration for the presentation purposes =============
# ============== This configuration assumes SampleDeck.apkg is imported =======
azure:
  # Relative path to a file that contains Azure API key.
  apiKeyFile: ./azure-key.txt
  endpointUrl: https://germanywestcentral.tts.speech.microsoft.com/cognitiveservices/v1
  voice: de-DE-KillianNeural
  minPauseBetweenRequests: 2100ms
  retryOnTooManyRequests: true
#  logRequests: true
anki:
  # NOTE: this is non-default port. If you didn't change it manually in yor plugin configuration,
  #       remove the following line so that anki-helper uses default AnkiConnect address.
  connectUrl: 'http://localhost:8766'
  # logRequests: true
actions:
  noteProcessing:
    # Resize all images stored in tag 'Image' to height 200, preserving the aspect ratio.
    - noteFilter: note:German* Image:_* -tag:image_resized
      exec:
        command: ./scripts/resize_image.py
        args:
          - Image
          - $$.Note.Fields.Image$$
          - "200"
          - image_resized
