azure:
  # Relative path to a file that contains Azure API key.
  apiKeyFile: azure-key.txt
  endpointUrl: https://germanywestcentral.tts.speech.microsoft.com/cognitiveservices/v1
  voice: en-GB-RyanNeural
  minPauseBetweenRequests: 2100ms
  retryOnTooManyRequests: true
#  logRequests: true
anki:
  # NOTE: this is non-default port. If you didn't change it manually in yor plugin configuration,
  #       remove the following line so that anki-helper uses default AnkiConnect address.
  connectUrl: 'http://localhost:8766'
  # logRequests: true
actions:
  tts:
    - textField: Word
      audioField: WordVoiceover
      noteFilter: "note:English* Word:_* WordVoiceover:"
      textPreprocessing:
        - regexp: '</?div>'
          replacement: ''
        - regexp: '&nbsp;'
          replacement: ''
        - regexp: '\{\{'
          replacement: ''
        - regexp: '\}\}'
          replacement: ''
        - regexp: '\s+'
          replacement: ' '
    - textField: Example1
      audioField: Example1Voiceover
      noteFilter: "note:English* Example1:_* Example1Voiceover:"
      textPreprocessing:
        - regexp: '</?div>'
          replacement: ''
        - regexp: '&nbsp;'
          replacement: ''
        - regexp: '\{\{'
          replacement: ''
        - regexp: '\}\}'
          replacement: ''
        - regexp: '\s+'
          replacement: ' '
    - textField: Example2
      audioField: Example2Voiceover
      noteFilter: "note:English* Example2:_* Example2Voiceover:"
      textPreprocessing:
        - regexp: '</?div>'
          replacement: ''
        - regexp: '&nbsp;'
          replacement: ''
        - regexp: '\{\{'
          replacement: ''
        - regexp: '\}\}'
          replacement: ''
        - regexp: '\s+'
          replacement: ' '
  noteProcessing:
    # Resize all images stored in tag 'Image' to height 200, preserving the aspect ratio.
    - noteFilter: note:English* Image:_* -tag:image_resized
      exec:
        command: ./scripts/resize_image.py
        args:
          - Image
          - $$.Note.Fields.Image$$
          - 200
          - image_resized
  cardsOrganization:
    - filter: note:English*
      targetDeck: English
