azure:
  # Relative path to a file that contains Azure API key.
  apiKeyFile: azure-key.txt
  endpointUrl: https://germanywestcentral.tts.speech.microsoft.com/cognitiveservices/v1
  voice: de-DE-KillianNeural
  minPauseBetweenRequests: 2100ms
  retryOnTooManyRequests: true
#  logRequests: true
anki:
  # NOTE: this is non-default port. If you didn't change it manually in yor plugin configuration,
  #       remove the following line so that anki-helper uses default AnkiConnect address.
  connectUrl: 'http://localhost:8766'
  # logRequests: true
actions:
  tts:
    - forGeneratedNoteType: GermanVerb
    - forGeneratedNoteType: GermanNoun
    - textField: Word
      audioField: WordVoiceover
      noteFilter: "note:German* Word:_* WordVoiceover:"
    - textField: WordExample
      audioField: WordExampleVoiceover
      noteFilter: "note:German* WordExample:_* WordExampleVoiceover:"
    - textField: Singular
      audioField: SingularVoiceover
      noteFilter: "note:German* Singular:_* SingularVoiceover:"
    - textField: SingularExample
      audioField: SingularExampleVoiceover
      noteFilter: "note:German* SingularExample:_* SingularExampleVoiceover:"
    - textField: Plural
      audioField: PluralVoiceover
      noteFilter: "note:German* Plural:_* PluralVoiceover:"
    - textField: PluralExample
      audioField: PluralExampleVoiceover
      noteFilter: "note:German* PluralExample:_* PluralExampleVoiceover:"
    - textField: NominativSingular
      audioField: NominativSingularVoiceover
      noteFilter: "note:German* NominativSingular:_* NominativSingularVoiceover:"
    - textField: NominativSingularExample
      audioField: NominativSingularExampleVoiceover
      noteFilter: "note:German* NominativSingularExample:_* NominativSingularExampleVoiceover:"
  noteTypes:
    - name: GermanVerb
      fields:
        - name: Infinitiv
          vars:
            pronoun: ""
            tense: Verb im Infinitiv
        - name: InfinitivExample

        - name: Explanation
          skipVoiceover: true
        - name: Synonyms
          skipVoiceover: true

        # Perfect is always (haben|sein) + Partizip II, so it doesn't make sense
        # to learn it for more than one pronoun.
        - name: PerfektIch
          vars:
            pronoun: "(im Perfekt) ich"
            tense: "Verb im Perfekt"
        - name: PerfektIchExample

        - name: IndicativPraesensIch
          vars:
            pronoun: "ich"
            pronounPostfix: ""
            tense: Verb im Präsens
        - name: IndicativPraesensIchExample
        - name: IndicativPraesensDu
          vars:
            pronoun: "du"
            pronounPostfix: ""
            tense: Verb im Präsens
        - name: IndicativPraesensDuExample
        - name: IndicativPraesensEr
          vars:
            pronoun: "er/sie/es"
            pronounPostfix: ""
            tense: Verb im Präsens
        - name: IndicativPraesensErExample
        - name: IndicativPraesensWir
          vars:
            pronoun: "wir"
            pronounPostfix: ""
            tense: Verb im Präsens
        - name: IndicativPraesensWirExample
        - name: IndicativPraesensIhr
          vars:
            pronoun: "ihr"
            pronounPostfix: ""
            tense: Verb im Präsens
        - name: IndicativPraesensIhrExample
        - name: IndicativPraesensSie
          vars:
            pronoun: "sie/Sie"
            pronounPostfix: ""
            tense: Verb im Präsens
        - name: IndicativPraesensSieExample

        - name: PraeteritumIch
          vars:
            pronoun: ich
            pronounPostfix: ""
            tense: Verb im Präteritum
        - name: PraeteritumIchExample
        - name: PraeteritumDu
          vars:
            pronoun: du
            pronounPostfix: ""
            tense: Verb im Präteritum
        - name: PraeteritumDuExample
        - name: PraeteritumEr
          vars:
            pronoun: er/sie/es
            pronounPostfix: ""
            tense: Verb im Präteritum
        - name: PraeteritumErExample
        - name: PraeteritumWir
          vars:
            pronoun: wir
            pronounPostfix: ""
            tense: Verb im Präteritum
        - name: PraeteritumWirExample
        - name: PraeteritumIhr
          vars:
            pronoun: ihr
            pronounPostfix: ""
            tense: Verb im Präteritum
        - name: PraeteritumIhrExample
        - name: PraeteritumSie
          vars:
            pronoun: sie/Sie
            pronounPostfix: ""
            tense: Verb im Präteritum
        - name: PraeteritumSieExample

        - name: ImperativDu
          vars:
            pronoun: "(du)"
            pronounPostfix: ", bitte"
            tense: Verb im Imperativ
        - name: ImperativDuExample
        - name: ImperativIhr
          vars:
            pronoun: "(ihr)"
            pronounPostfix: ", bitte"
            tense: Verm im Imperativ
        - name: ImperativIhrExample
      templates:
        - name: "$$.Field$$"
          forFields:
            - Infinitiv
            - PerfektIch
            - IndicativPraesensIch
            - IndicativPraesensDu
            - IndicativPraesensEr
            - IndicativPraesensWir
            - IndicativPraesensIhr
            - IndicativPraesensSie
            - PraeteritumIch
            - PraeteritumDu
            - PraeteritumEr
            - PraeteritumWir
            - PraeteritumIhr
            - PraeteritumSie
            - ImperativDu
            - ImperativIhr
          front: |
            <h2>$$.Vars.tense$$</h2>
            
            <div><i>{{text:Explanation}}</i></div><br>
            
            {{#Synonyms}}
              <div>
                Synonyme: {{Synonyms}}
              </div>
            {{/Synonyms}}

            <div>$$.Vars.pronoun$$ <b><span class='cloze'>[&#8230;]</span></b>$$.Vars.pronounPostfix$$</div>
            
            {{#$$.Field$$Example}}
              <br>
              <div>
                Beispiel:<br><span class="mycloze">{{$$.Field$$Example}}</span>
              </div>
            {{/$$.Field$$Example}}
            
            {{type:$$.Field$$}}
            
            <script>
            var clozes = document.querySelectorAll(".mycloze");
            clozes.forEach(function (elem) {
                var html = elem.innerHTML;
                while (true) {
                    var beginIdx = html.indexOf("{" + "{");
                    if (beginIdx < 0) {
                        break;
                    }
                    var endIdx = html.indexOf("}" + "}", beginIdx);
                    if (endIdx < 0) {
                        break;
                    }
                    html = html.substring(0, beginIdx) + "<b><span class='cloze'>[&#8230;]</span></b>" + html.substring(endIdx + 2);
                }
            
                elem.innerHTML = html;
            });
            </script>
          back: |
            <h2>$$.Vars.tense$$</h2>
            
            <div><i>{{text:Explanation}}</i></div><br>
            
            {{#Synonyms}}
              <div>
                Synonyme: {{Synonyms}}
              </div>
            {{/Synonyms}}

            <div>$$.Vars.pronoun$$ <b><span class='cloze'>{{text:$$.Field$$}}</span></b>$$.Vars.pronounPostfix$${{$$.FieldVoiceover$$}}</div>
            
            {{#$$.Field$$Example}}
              <br>
              <div>
                Beispiel:<br><span class="mycloze">{{$$.Field$$Example}}</span> {{$$.Field$$ExampleVoiceover}}
              </div>
            {{/$$.Field$$Example}}
            
            <hr id=answer>
            {{type:$$.Field$$}}
            
            <script>
            var clozes = document.querySelectorAll(".mycloze");
            clozes.forEach(function (elem) {
                var html = elem.innerHTML;
                while (true) {
                    var beginIdx = html.indexOf("{" + "{");
                    if (beginIdx < 0) {
                        break;
                    }

                    var endIdx = html.indexOf("}" + "}", beginIdx);
                    if (endIdx < 0) {
                        break;
                    }
                    html = html.substring(0, beginIdx) +
                        "<b><span class='cloze'>" +
                        html.substring(beginIdx+2, endIdx) +
                        "</span></b>" +
                        html.substring(endIdx + 2);
                }

                elem.innerHTML = html;
            });
            </script>
      css: |
        .card {
          font-family: arial;
          font-size: 20px;
          text-align: center;
          color: black;
          background-color: white;
        }

        .cloze {
         font-weight: bold;
         color: blue;
        }
    - name: GermanNoun
      fields:
        - name: Explanation
          skipVoiceover: true
        - name: Synonyms
          skipVoiceover: true

        - name: SingularNominativ
          vars:
            preposition: ""
            case: |
              <div class="singular">Einzahl Substantiv im Nominativ</div>
        - name: SingularNominativExample
        - name: PluralNominativ
          vars:
            preposition: ""
            case: |
              <div class="plural">Plural Substantiv im Nominativ</div>
        - name: PluralNominativExample

        - name: Image
          skipVoiceover: true


        - name: SingularAkkusativ
          vars:
            preposition: "ich habe"
            case: |
              <div class="singular">Einzahl Substantiv im Akkusativ</div>
        - name: SingularAkkusativExample
        - name: SingularDativ
          vars:
            preposition: "mit"
            case: |
              <div class="singular">Einzahl Substantiv im Dativ</div>
        - name: SingularDativExample
        - name: SingularGenitiv
          vars:
            preposition: "das Zeug"
            case: |
              <div class="singular">Einzahl Substantiv im Genitiv</div>
        - name: SingularGenitivExample

        - name: Gender
          skipVoiceover: true
      templates:
        - name: "$$.Field$$"
          forFields:
            - SingularNominativ
            - PluralNominativ
            - SingularAkkusativ
            - SingularDativ
            - SingularGenitiv
          front: |
            $$.Vars.case$$

            {{Image}}

            <br>
            <div>{{Explanation}}</div>


            {{#Synonyms}}
              <div>
                Synonyme: {{Synonyms}}
              </div>
            {{/Synonyms}}
            
            $$if .Vars.preposition$$
              <div>$$.Vars.preposition$$ <b><span class='cloze'>[&#8230;]</span></b></div>
            $$end$$

            {{#$$.Field$$Example}}
              <br>
              <div>
                Beispiel:<br><span class="mycloze">{{$$.Field$$Example}}</span>
              </div>
            {{/$$.Field$$Example}}

            {{type:$$.Field$$}}

            <script>
            var clozes = document.querySelectorAll(".mycloze");
            clozes.forEach(function (elem) {
                var html = elem.innerHTML;
                while (true) {
                    var beginIdx = html.indexOf("{" + "{");
                    if (beginIdx < 0) {
                        break;
                    }
                    var endIdx = html.indexOf("}" + "}", beginIdx);
                    if (endIdx < 0) {
                        break;
                    }
                    html = html.substring(0, beginIdx) + "<b><span class='cloze'>[&#8230;]</span></b>" + html.substring(endIdx + 2);
                }

                elem.innerHTML = html;
            });
            </script>

          back: |
            $$.Vars.case$$
            
            <div>
                $$.Vars.preposition$$ <b><span class='cloze'>{{text:$$.Field$$}}</span></b>

            	{{#Gender}}
            		<span class="gender">
              		<span class="{{Gender}}">[{{Gender}}]</span>
            		</span>
            	{{/Gender}}
            	{{$$.Field$$Voiceover}}
            </div>

            {{Image}}

            <div>{{Explanation}}</div>

            {{#Synonyms}}
            	<br>
              <div>
                Synonyme: {{Synonyms}}
              </div>
            {{/Synonyms}}

            {{#$$.Field$$Example}}
            	<br>
              <div>
                Beispiel:<br><span class="mycloze">{{$$.Field$$Example}}</span>{{$$.Field$$ExampleVoiceover}}
              </div>
            {{/$$.Field$$Example}}

            <hr id="answer">

            {{type:$$.Field$$}}

            <script>
            var clozes = document.querySelectorAll(".mycloze");
            clozes.forEach(function (elem) {
                var html = elem.innerHTML;
                while (true) {
                    var beginIdx = html.indexOf("{" + "{");
                    if (beginIdx < 0) {
                        break;
                    }

                    var endIdx = html.indexOf("}" + "}", beginIdx);
                    if (endIdx < 0) {
                        break;
                    }
                    html = html.substring(0, beginIdx) +
                        "<b><span class='cloze'>" +
                        html.substring(beginIdx+2, endIdx) +
                        "</span></b>" +
                        html.substring(endIdx + 2);
                }

                elem.innerHTML = html;
            });
            </script>

      css: |
        .card {
          font-family: arial;
          font-size: 20px;
          text-align: center;
          color: black;
          background-color: white;
        }

        .cloze {
          font-weight: bold;
          color: blue;
        }

        .gender{
          font-style: italic;
          font-size: 60%;
        }

        .Maskulinum {
        	font-weight: bold;
          color: blue;
        }

        .Femininum {
        	font-weight: bold;
          color: hotpink;
        }

        .Neutrum {
          font-weight: bold;
          color: green;
        }

        .singular {
          font-style: italic;
        }

        .plural {
          font-style: normal;
          font-weight: bold;
        }

  noteProcessing:
    - noteFilter: "note:GermanNoun SingularNominativ:_* Gender:"
      exec:
        command: ./scripts/deduce_german_gender.py
        args:
          - $$.Note.Fields.SingularNominativ$$
    - noteFilter: |
        note:GermanNoun SingularNominativ:_* -tag:skip_cases (
          (SingularAkkusativ: -tag:noun_form:SingularAkkusativ)
          OR (SingularDativ: -tag:noun_form:SingularDativ)
          OR (SingularGenitiv: -tag:noun_form:SingularGenitiv)
        )
#      exec:
#        command: echo
#        args:
#          - '[{"add_tag": "skip_cases"}]'
      exec:
        command: /usr/bin/env
        args:
          - go
          - run
          - $$ resolve_path "./scripts/german_word_forms.go" $$
          - noun
          - $$.Note.Fields.SingularNominativ$$
          - $$ .Note.Tags | to_json $$
      minPauseBetweenExecutions: 1200ms
      timeout: 5s
    - noteFilter: |
        note:GermanVerb -tag:skip_conjugation (
        (IndicativPraesensIch: -tag:conjugation_done:IndicativPraesensIch)
          OR (IndicativPraesensDu: -tag:conjugation_done:IndicativPraesensDu)
          OR (IndicativPraesensEr: -tag:conjugation_done:IndicativPraesensEr)
          OR (IndicativPraesensWir: -tag:conjugation_done:IndicativPraesensWir)
          OR (IndicativPraesensIhr: -tag:conjugation_done:IndicativPraesensIhr)
          OR (IndicativPraesensSie: -tag:conjugation_done:IndicativPraesensSie)
          OR (ImperativDu: -tag:conjugation_done:ImperativDu)
          OR (ImperativIhr: -tag:conjugation_done:ImperativIhr)
          OR (PraeteritumIch: -tag:conjugation_done:PraeteritumIch)
          OR (PraeteritumDu: -tag:conjugation_done:PraeteritumDu)
          OR (PraeteritumEr: -tag:conjugation_done:PraeteritumEr)
          OR (PraeteritumWir: -tag:conjugation_done:PraeteritumWir)
          OR (PraeteritumIhr: -tag:conjugation_done:PraeteritumIhr)
          OR (PraeteritumSie: -tag:conjugation_done:PraeteritumSie)
          OR (PerfektIch: -tag:conjugation_done:PerfektIch)
        )
#      exec:
#        command: echo
#        args:
#          - '[{"add_tag": "skip_conjugation"}]'
      exec:
        command: /usr/bin/env
        args:
          - go
          - run
          - $$ resolve_path "./scripts/german_word_forms.go" $$
          - verb
          - $$.Note.Fields.Infinitiv$$
          - $$ .Note.Tags | to_json $$
      minPauseBetweenExecutions: 1200ms
      timeout: 5s
    # Resize all images stored in tag 'Image' to height 200, preserving the aspect ratio.
    - noteFilter: note:German* Image:_* -tag:image_resized
      exec:
        command: ./scripts/resize_image.py
        args:
          - Image
          - $$.Note.Fields.Image$$
          - "200"
          - image_resized
  cardsOrganization:
    - filter: -note:GermanVerb* -card:SingularAkkusativ -card:SingularDativ -card:SingularGenitiv note:German*
      targetDeck: German::00_Other
    - filter: note:GermanVerb* (card:*Infinitiv* OR card:*Perfekt*)
      targetDeck: German::01_VerbsInfinitive
    - filter: note:GermanVerb* -card:*Infinitiv* -card:*Perfekt*
      targetDeck: German::02_WordForms
    - filter: note:GermanNoun (card:SingularAkkusativ OR card:SingularDativ OR card:SingularGenitiv)
      targetDeck: German::02_WordForms
